version: "3.8"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: datamaq
      MYSQL_USER: datamaq
      MYSQL_PASSWORD: datamaq
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DB: datamaq
      MYSQL_USER: datamaq
      MYSQL_PASSWORD: datamaq
      STATIC_PATH: /app/static
    ports:
      - "5000:5000"
    volumes:
      - .:/app

volumes:
  db_data: